// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATnJ5OrvDbYWNOd5n_U-QJstDeLS9E7Qc',
    appId: '1:755570042998:web:992fbb3d54bc28b6c1d757',
    messagingSenderId: '755570042998',
    projectId: 'laporbook-93e06',
    authDomain: 'laporbook-93e06.firebaseapp.com',
    storageBucket: 'laporbook-93e06.appspot.com',
    measurementId: 'G-GMZ2RVKLEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtZzTHeAYTUmjyQwwkebUED_4U102FyOY',
    appId: '1:755570042998:android:e78caa47adb78301c1d757',
    messagingSenderId: '755570042998',
    projectId: 'laporbook-93e06',
    storageBucket: 'laporbook-93e06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZZ4nx1lsmgi7VcfPXFcrliBvXRiyB7-E',
    appId: '1:755570042998:ios:b9d38336b3410437c1d757',
    messagingSenderId: '755570042998',
    projectId: 'laporbook-93e06',
    storageBucket: 'laporbook-93e06.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );
}
